# Generated by Django 3.2.7 on 2021-09-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trabajador', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trabajador',
            name='email_usuario',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='trabajador',
            name='telefono_usuario',
            field=models.IntegerField(verbose_name='Teléfono'),
        ),
    ]
