export const GET_TRABAJADOR = "GET_TRABAJADOR";
export const DELETE_TRABAJADOR = "DELETE_TRABAJADOR";
export const ADD_TRABAJADOR = "ADD_TRABAJADOR";
export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const UPDATE_TRABAJADOR = "UPDATE_TRABAJADOR";






